language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: PWeRzLZ0yuroUekkggmm0rL/qF2bFWxDleR79wkL5Ovg6w2ku7ONBp2uGtAarwZYokhRIWExLSGoG8/irfYTQYcdNOfOKtwAMNRjhWmndwLExyI7NekOtp7UamW+8PlaLeO6UmlIpDuZDcGeAaO7uHRsT3+HnFJhIlVrEEga1s48FGdchYvnJ/vmpzHAc26F1MKv4xZKw4WqssdnwoZ+Bcd6AQxMxPF1MOHPVxChd1wIi4IhpBghdU6k8aBAVohYSfpzZTSzKrHW6WBg0hWJs9O8lrZOajiXzg7bcCQ5/2TeX4Z2971iC6V/9z2phkN8uZsqHu5wFh3enTqTZFQDqaKhKZHmCZfMw9kC83lmZvv2G15CtxzeaNzWhiTbzS64qgIeHjCnDRUdRVm1totrw9dAIgTDT5y+T8v9+EDSIP9YS4N3VBQl2Dk2HuEnh+cCcUAu028ETWexnzo29tPSke7yoUa/nH1wTjxZM6V3bSjwpnvpqRlKND1K6Jg3o9KiJ2/B6546HBqevJiV6W8HOuKUN1axLL22IYkgRzkJOpLe7UVduho0uCZ6SNq3CW8Gn9PBLjO7+9Db7suGK6y4mFITDAbPr5WmOKVnZETjuQDoMGX53CU4NbtB5fvbZz4Z3RPFHiJ/Lpodfg86XqhSPVdLjbTkxELTrIw4H8AzCm4=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: FDQxZrM3x2sBBd3nsG9QLOIKk8z79FdjnWrpyThStUPCz8UUjcIt+6QssbIkJxSDWO+TtNOUOPgzQHSIrWQXpYWG6Thgj+VUjaR+xrbHXPlPo1l0FHhQd/FLT40mZ8EMPsROzMl5KdOif94+IaKVz06Ab1SXd3uNYR+kVCYmbEpb1B6hXGIopsYR2JjSxSfvqazMMC0DO2vx3iq/n4mnE6oJ76DGnR5ip3X2zPv+91GQiL7OjgEr0xDUAqetjs9QCpYTgRIFgngOOv1k1jTgvJDzx5S9RHiarL5ScF0/2wjLi86tm38qVQdeocBti9NGWEhcx4Kyt4b+/0kMJPyo635i/JhT3XmbIGBTc4MfLa15SuIkhqW2af2Hc3z1lkTEloc89n0VPNC+8HtG0JWv1s5akMP1XbKZFDcx0Mj1BwMw0UlhD95orJHKIEBPg3LPvA5JTentPisAh/pAPlW/mxmoXLTqMdJC1v8StWXOMESWbBGMGsISb0eIrRFfj3ofSyPU7LGpcMlSyo2vKWZecNP0odkbMNorFHQCPJPWfXgkJEqJKhE6A7nT6Vr0GOJS1ERI2tx5+68Mq2VXgT4Edm9RO3NKejFOaxDnoQ4JIUxMTGPdjD950n2fThs3aRR5sFZfrDeLS2i26le9CCLZNRAHXripLa/jnHd90KBq9dQ=
sudo: false
